/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "cmsis_os.h"


static volatile uint32_t cnt1;
static volatile uint32_t cnt2;


void Task1(void * args){

	while(1){
		cnt1++;
		osThreadYield();
	}
}

void Task2(void * args){

	while(1){
		cnt2++;
		osThreadYield();
	}
}

int main(void){

	osKernelInitialize();

	osThreadNew(Task1, NULL, NULL);
	osThreadNew(Task2, NULL, NULL);

//	osKernelStart();

	while(1){

	}

}

